### ISSUE TITLE
rgbify not working?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/rio-rgbify#12]
root@ubuntu:/mapbox/rio-rgbify# rio rgbify

Rio utility v1.07 - The Snowblind Alliance (c) 1999
----------------------------------------------------
command line switches available :-
	-d  display directory
	-iy initialize with check for bad blocks
	-in initialize without check for bad blocks
	-x  perform operations on external flash ram
	-u  specify file(s) to upload
	-g  specify file to download
	-f  specify text based playlist file which contains files to be upload
	-z  specify file to delete
	-za delete all files
	-o  specify new playlist order in quotes
	-p  specify parallel port base IO address, default=0x378
	-v  enable verbose mode
	-di specify initialization delay (default is 20000)
	-dt specify tx delay (default is 100)
	-dr specify rx delay (default is 2)

**Comment by sgillies** [comment]
I'm sorry, but you're running the wrong rio program. That's the rio mp3 player.
